on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $pr
        env:
          pr: ${{ toJson(github.event.issue.pull_request) }}
