on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          pr="$(curl -fsSL -H "Authorization: token $token" $pr_url)"
          echo "$pr"
        env:
          token: ${{ github.token }}
          pr_url: ${{ github.event.issue.pull_request.url }}
